const GET_BOOKMARKS_AND_ASSIGNMENTS = 'GET_BOOKMARKS_AND_ASSIGNMENTS';
const GET_BOOKMARKS_AND_ASSIGNMENTS_SUCCESS = 'GET_BOOKMARKS_AND_ASSIGNMENTS_SUCCESS';
const GET_BOOKMARKS_AND_ASSIGNMENTS_ERROR = 'GET_BOOKMARKS_AND_ASSIGNMENTS_ERROR';
const GET_BOOKMARKS_ERROR_AND_ASSIGNMENTS_SUCCESS = 'GET_BOOKMARKS_ERROR_AND_ASSIGNMENTS_SUCCESS';
const GET_BOOKMARKS_SUCCESS_AND_ASSIGNMENTS_ERROR = 'GET_BOOKMARKS_SUCCESS_AND_ASSIGNMENTS_ERROR';

const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
const REMOVE_BOOKMARK_ERROR = 'REMOVE_BOOKMARK_ERROR';

const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';
const REMOVE_ASSIGNMENT_SUCCESS = 'REMOVE_ASSIGNMENT_SUCCESS';
const REMOVE_ASSIGNMENT_ERROR = 'REMOVE_ASSIGNMENT_ERROR';

const RESET = 'RESET';

export {
  GET_BOOKMARKS_AND_ASSIGNMENTS,
  GET_BOOKMARKS_AND_ASSIGNMENTS_SUCCESS,
  GET_BOOKMARKS_AND_ASSIGNMENTS_ERROR,
  GET_BOOKMARKS_ERROR_AND_ASSIGNMENTS_SUCCESS,
  GET_BOOKMARKS_SUCCESS_AND_ASSIGNMENTS_ERROR,

  REMOVE_BOOKMARK,
  REMOVE_BOOKMARK_SUCCESS,
  REMOVE_BOOKMARK_ERROR,

  REMOVE_ASSIGNMENT,
  REMOVE_ASSIGNMENT_SUCCESS,
  REMOVE_ASSIGNMENT_ERROR,

  RESET
}