const ADD_CONTENT = 'ADD_CONTENT';
const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
const ADD_CONTENT_ERROR = 'ADD_CONTENT_ERROR';

const ADD_FEED = 'ADD_FEED';
const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';
const ADD_FEED_ERROR = 'ADD_FEED_ERROR';

const CHECK_URL = 'CHECK_URL';
const CHECK_URL_SUCCESS = 'CHECK_URL_SUCCESS';
const CHECK_URL_ERROR = 'CHECK_URL_ERROR';

const REFRESH_STATE = 'REFRESH_STATE';

export {
  ADD_CONTENT,
  ADD_CONTENT_SUCCESS,
  ADD_CONTENT_ERROR,

  ADD_FEED,
  ADD_FEED_SUCCESS,
  ADD_FEED_ERROR,

  CHECK_URL,
  CHECK_URL_SUCCESS,
  CHECK_URL_ERROR,

  REFRESH_STATE
};
