const BOOKMARK_CONTENT = 'BOOKMARK_CONTENT';
const BOOKMARK_CONTENT_SUCCESS = 'BOOKMARK_CONTENT_SUCCESS';
const BOOKMARK_CONTENT_ERROR = 'BOOKMARK_CONTENT_ERROR';

const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
const REMOVE_BOOKMARK_ERROR = 'REMOVE_BOOKMARK_ERROR';

const ASSIGN_CONTENT = 'ASSIGN_CONTENT';
const ASSIGN_CONTENT_SUCCESS = 'ASSIGN_CONTENT_SUCCESS';
const ASSIGN_CONTENT_ERROR = 'ASSIGN_CONTENT_ERROR';

const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT';
const REMOVE_ASSIGNMENT_SUCCESS = 'REMOVE_ASSIGNMENT_SUCCESS';
const REMOVE_ASSIGNMENT_ERROR = 'REMOVE_ASSIGNMENT_ERROR';

const GET_ERRORS = 'GET_ERRORS';

const REFRESH_STATE = 'REFRESH_STATE';

export {
  BOOKMARK_CONTENT,
  BOOKMARK_CONTENT_SUCCESS,
  BOOKMARK_CONTENT_ERROR,

  REMOVE_BOOKMARK,
  REMOVE_BOOKMARK_SUCCESS,
  REMOVE_BOOKMARK_ERROR,

  ASSIGN_CONTENT,
  ASSIGN_CONTENT_SUCCESS,
  ASSIGN_CONTENT_ERROR,

  REMOVE_ASSIGNMENT,
  REMOVE_ASSIGNMENT_SUCCESS,
  REMOVE_ASSIGNMENT_ERROR,

  GET_ERRORS,

  REFRESH_STATE
};
