const CONTENT_START_LOADING = 'CONTENT_START_LOADING';
const CONTENT_FINISH_LOADING = 'CONTENT_FINISH_LOADING';
const GET_CONTENTS = 'GET_CONTENTS';
const GET_CONTENTS_SUCCESS = 'GET_CONTENTS_SUCCESS';
const GET_CONTENTS_ERROR = 'GET_CONTENTS_ERROR';

const ADD_BOOKMARK = 'ADD_BOOKMARK';
const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';

const ASSIGN_ME = 'ASSIGN_ME';
const UN_ASSIGN_ME = 'UN_ASSIGN_ME';
const GET_ERRORS = 'GET_ERRORS';

const PARSE_RSS = 'PARSE_RSS';
const PARSE_RSS_SUCCESS = 'PARSE_RSS_SUCCESS';
const PARSE_RSS_ERROR = 'PARSE_RSS_ERROR';

const REFRESH_STATE = 'REFRESH_STATE';

export {
  CONTENT_START_LOADING,
  CONTENT_FINISH_LOADING,

  GET_CONTENTS,
  GET_CONTENTS_SUCCESS,
  GET_CONTENTS_ERROR,

  ADD_BOOKMARK,
  REMOVE_BOOKMARK,

  ASSIGN_ME,
  UN_ASSIGN_ME,

  GET_ERRORS,

  PARSE_RSS,
  PARSE_RSS_SUCCESS,
  PARSE_RSS_ERROR,

  REFRESH_STATE
};
